export const actionCards = [
  {
    id: "question-guildmaster",
    label: "Summon Guildmaster Varro privately",
    detail: "Question him about missing grain shipments while keeping the tone cordial.",
    centerNodeId: "merchants",
    structural: {
      intent: "investigate",
      channel: "private court pressure",
      target: "merchants",
      tone: "cordial but probing",
      visibility: "private",
    },
    log: {
      title: "Private questioning of Guildmaster Varro",
      summary: "The prince questioned Varro about missing shipments without making a public accusation.",
      domainTags: ["trade", "food", "investigation"],
      acesTags: ["conductance", "distortion", "legitimacy"],
      involvedNodes: ["court", "merchants"],
      visibility: "private",
      knowledge: "suspected",
    },
    effects: {
      merchants: { tension: 3, legitimacy: -1, conductance: -2 },
      court: { memoryLoad: 2 },
    },
    edgeEffects: [
      { from: "court", to: "merchants", trust: -2, secrecy: 2, distortion: -2 },
    ],
  },
  {
    id: "support-soup-kitchens",
    label: "Ask Archbishop Sera for public mercy",
    detail: "Support church soup kitchens and make the gesture visible without calling it panic.",
    centerNodeId: "church",
    structural: {
      intent: "stabilize legitimacy",
      channel: "church symbolism",
      target: "population",
      tone: "public mercy",
      visibility: "public",
    },
    log: {
      title: "Public support for church kitchens",
      summary: "The prince backed church kitchens as an act of mercy before winter pressure hardened.",
      domainTags: ["food", "religion", "mercy"],
      acesTags: ["legitimacy", "participation", "tension"],
      involvedNodes: ["church", "population", "court"],
      visibility: "public",
      knowledge: "public",
    },
    effects: {
      population: { legitimacy: 4, tension: -4, participation: 3 },
      church: { legitimacy: 3, conductance: 2 },
      court: { legitimacy: 1 },
    },
  },
  {
    id: "increase-patrols",
    label: "Send the captain quietly through the market",
    detail: "Increase visible order, but instruct the captain to listen before intimidating anyone.",
    centerNodeId: "population",
    structural: {
      intent: "contain unrest",
      channel: "military presence",
      target: "population",
      tone: "restrained",
      visibility: "local",
    },
    log: {
      title: "Restrained market patrol",
      summary: "A captain walked the market under orders to listen first and display force second.",
      domainTags: ["security", "rumor", "market"],
      acesTags: ["tension", "legitimacy", "participation"],
      involvedNodes: ["military", "population"],
      visibility: "local",
      knowledge: "witnessed",
    },
    effects: {
      population: { tension: -2, legitimacy: -1, participation: -1 },
      military: { legitimacy: 1, concentration: 1 },
    },
  },
  {
    id: "listen-to-cook",
    label: "Let Cook Elian continue speaking",
    detail: "Delay the council schedule and let the kitchen account of flour sacks unfold.",
    centerNodeId: "population",
    structural: {
      intent: "read hidden pressure",
      channel: "servant testimony",
      target: "population",
      tone: "patient",
      visibility: "private",
    },
    log: {
      title: "Cook Elian describes old flour sacks",
      summary: "The kitchen reported flour sacks arriving with old dust and inconsistent seals.",
      domainTags: ["food", "servants", "evidence"],
      acesTags: ["memoryLoad", "distortion", "conductance"],
      involvedNodes: ["population", "merchants", "court"],
      visibility: "private",
      knowledge: "witnessed",
    },
    effects: {
      population: { participation: 2, memoryLoad: 2 },
      court: { memoryLoad: 3 },
      merchants: { distortion: 3, tension: 2 },
    },
  },
];

export const proxyCards = [
  {
    id: "shortage-pressure",
    name: "Shortage Pressure",
    triggerTags: ["food"],
    effects: {
      population: { tension: 2, optionality: -1 },
      merchants: { legitimacy: -1, conductance: -1 },
      blackMarket: { optionality: 2, conductance: 1 },
    },
    cue: "Food pressure searches for hidden paths.",
  },
  {
    id: "rumor-acceleration",
    name: "Rumor Acceleration",
    triggerTags: ["rumor"],
    effects: {
      population: { tension: 2, memoryLoad: 1 },
      blackMarket: { conductance: 2 },
      court: { distortion: 2 },
    },
    cue: "Rumor begins moving faster than official speech.",
  },
  {
    id: "symbolic-mercy",
    name: "Symbolic Mercy",
    triggerTags: ["mercy", "religion"],
    effects: {
      population: { legitimacy: 2, tension: -2 },
      church: { participation: 2 },
      court: { legitimacy: 1 },
    },
    cue: "Mercy converts pressure into participation for a moment.",
  },
  {
    id: "coercive-overreach",
    name: "Coercive Overreach",
    triggerTags: ["security"],
    effects: {
      population: { tension: 1, optionality: -2 },
      military: { concentration: 2 },
      court: { legitimacy: -1 },
    },
    cue: "Order improves, but the room for voluntary motion narrows.",
  },
  {
    id: "archive-reconstructability",
    name: "Archive Reconstructability",
    triggerTags: ["evidence", "investigation"],
    effects: {
      court: { reconstructability: 2, memoryLoad: 1 },
      merchants: { distortion: -1 },
    },
    cue: "Recorded contradiction becomes future leverage.",
  },
];

export const injectorCards = [
  {
    id: "refugee-caravan",
    name: "Refugee Caravan",
    everyTurns: 4,
    title: "A small refugee caravan reaches the north road",
    summary: "The travelers bring careful stories of failed harvests beyond the border.",
    domainTags: ["external", "food", "mercy"],
    acesTags: ["tension", "participation", "legitimacy"],
    involvedNodes: ["population", "church", "court"],
    visibility: "local",
    knowledge: "rumor",
  },
  {
    id: "dock-dispute",
    name: "Dock Dispute",
    everyTurns: 5,
    title: "A dock dispute vanishes from the official ledger",
    summary: "Merchants call it routine, but porters mention a sealed warehouse and a late military escort.",
    domainTags: ["trade", "rumor", "security"],
    acesTags: ["distortion", "conductance", "memoryLoad"],
    involvedNodes: ["merchants", "blackMarket", "military"],
    visibility: "factional",
    knowledge: "suspected",
  },
];
