export const initialNodes = [
  {
    id: "court",
    name: "Court",
    representative: "Steward Maran",
    description: "Protocol, decrees, treasury habits, and noble visibility.",
    profile: {
      legitimacy: 58,
      optionality: 48,
      reconstructability: 54,
      tension: 34,
      concentration: 55,
      adaptability: 42,
      participation: 40,
      conductance: 52,
      memoryLoad: 28,
    },
  },
  {
    id: "population",
    name: "Population",
    representative: "Cook Elian",
    description: "Street mood, hunger, rumor texture, and everyday legitimacy.",
    profile: {
      legitimacy: 52,
      optionality: 44,
      reconstructability: 45,
      tension: 46,
      concentration: 38,
      adaptability: 51,
      participation: 56,
      conductance: 50,
      memoryLoad: 34,
    },
  },
  {
    id: "merchants",
    name: "Merchants",
    representative: "Guildmaster Varro",
    description: "Trade, ledgers, supply routes, bargaining power, and dependency.",
    profile: {
      legitimacy: 49,
      optionality: 62,
      reconstructability: 46,
      tension: 38,
      concentration: 58,
      adaptability: 56,
      participation: 42,
      conductance: 63,
      memoryLoad: 30,
    },
  },
  {
    id: "church",
    name: "Church",
    representative: "Archbishop Sera",
    description: "Meaning, mercy, ritual legitimacy, and moral interpretation.",
    profile: {
      legitimacy: 64,
      optionality: 40,
      reconstructability: 60,
      tension: 28,
      concentration: 42,
      adaptability: 38,
      participation: 61,
      conductance: 57,
      memoryLoad: 45,
    },
  },
  {
    id: "military",
    name: "Military",
    representative: "General Odran",
    description: "Force, order, obedience, border fear, and coercive stability.",
    profile: {
      legitimacy: 55,
      optionality: 36,
      reconstructability: 50,
      tension: 41,
      concentration: 64,
      adaptability: 34,
      participation: 32,
      conductance: 49,
      memoryLoad: 31,
    },
  },
  {
    id: "blackMarket",
    name: "Black Market",
    representative: "Tavern Broker Nessa",
    description: "Shadow conductance, hidden supply, rumor routes, and informal repair.",
    profile: {
      legitimacy: 28,
      optionality: 67,
      reconstructability: 35,
      tension: 52,
      concentration: 37,
      adaptability: 74,
      participation: 48,
      conductance: 59,
      memoryLoad: 39,
    },
  },
];

export const initialEdges = [
  { from: "court", to: "population", type: "authority", conductance: 54, trust: 47, distortion: 28, dependency: 45, secrecy: 25 },
  { from: "court", to: "merchants", type: "tax", conductance: 48, trust: 43, distortion: 30, dependency: 55, secrecy: 33 },
  { from: "court", to: "military", type: "force", conductance: 67, trust: 59, distortion: 22, dependency: 61, secrecy: 30 },
  { from: "court", to: "church", type: "symbol", conductance: 51, trust: 53, distortion: 25, dependency: 36, secrecy: 20 },
  { from: "military", to: "merchants", type: "security", conductance: 45, trust: 39, distortion: 33, dependency: 42, secrecy: 34 },
  { from: "merchants", to: "population", type: "trade", conductance: 68, trust: 41, distortion: 31, dependency: 66, secrecy: 35 },
  { from: "population", to: "church", type: "faith", conductance: 62, trust: 64, distortion: 18, dependency: 42, secrecy: 16 },
  { from: "population", to: "blackMarket", type: "rumor", conductance: 58, trust: 34, distortion: 49, dependency: 46, secrecy: 72 },
  { from: "merchants", to: "blackMarket", type: "shadow", conductance: 43, trust: 29, distortion: 54, dependency: 52, secrecy: 78 },
];

export const prince = {
  name: "Prince Alaric",
  traitBudget: 393,
  traitMin: 30,
  traitMax: 80,
  traits: {
    presence: 62,
    perception: 54,
    composure: 46,
    empathy: 61,
    resolve: 55,
    cunning: 43,
    vitality: 72,
  },
};

export const advisors = [
  {
    id: "steward",
    nodeId: "court",
    name: "Steward Maran",
    role: "Steward",
    lens: "efficiency, accounts, logistics, central order",
    watches: ["concentration", "conductance", "legitimacy"],
  },
  {
    id: "spymaster",
    nodeId: "blackMarket",
    name: "Ilyra",
    role: "Spymaster",
    lens: "secrecy, contradictions, rumor velocity, hidden incentives",
    watches: ["tension", "memoryLoad", "conductance"],
  },
  {
    id: "general",
    nodeId: "military",
    name: "General Odran",
    role: "General",
    lens: "force readiness, unrest, obedience, border risk",
    watches: ["tension", "concentration", "legitimacy"],
  },
  {
    id: "archbishop",
    nodeId: "church",
    name: "Archbishop Sera",
    role: "Archbishop",
    lens: "mercy, symbolic coherence, moral legitimacy",
    watches: ["legitimacy", "participation", "memoryLoad"],
  },
];
